from pyxtal.symmetry import Group

output_lines = []
output_lines.append("# Autogenerated Wyckoff position cache")
output_lines.append("from dataclasses import dataclass\n")
output_lines.append("@dataclass(frozen=True)")
output_lines.append("class WyckoffData:")
output_lines.append("    label: str")
output_lines.append("    frozen_axes: tuple[int, ...]\n")
output_lines.append("wyckoff_data = {")

for sg_number in range(1, 231):
    try:
        group = Group(sg_number)
        output_lines.append(f"  {sg_number}: {{")
        for wp in group.Wyckoff_positions:
            try:
                xyz_str = wp.gen_pos().as_xyz_str().replace('"', '\\"')
                frozen_axes = tuple(wp.get_frozen_axis())
                output_lines.append(
                    f'    "{wp.letter}": WyckoffData(label="{xyz_str}", frozen_axes={frozen_axes}),'
                )
            except Exception as e:
                output_lines.append(
                    f'    "{wp.letter}": WyckoffData(label="Error: {e}", frozen_axes=()),'
                )
        output_lines.append("  },")
    except Exception as e:
        output_lines.append(f"  {sg_number}: {{'error': 'Failed: {e}'}},")

output_lines.append("}")

with open("wyckoff_data.py", "w", encoding="utf-8") as f:
    f.write("\n".join(output_lines))

print("✅ wyckoff_data.py created successfully!")
