from pyxtal.symmetry import Group
import math
import re
import numpy as np
from ase.geometry import cellpar_to_cell
from functools import cached_property

lattice_fixed_params = {
    "triclinic":    {},
    "monoclinic":   { 'α': 90., 'γ': 90. },
    "orthorhombic": { 'α': 90., 'β': 90., 'γ': 90. },
    "tetragonal":   { 'b': 'a', 'α': 90., 'β': 90., 'γ': 90. },
    "hexagonal":    { 'b': 'a', 'α': 90., 'β': 90., 'γ': 120. },
    "trigonal": { 'b': 'a', 'α': 90., 'β': 90., 'γ': 120. },
    "trigonal-rhombohedral"   : { 'b': 'a', 'c': 'a', 'β': 'α', 'γ': 'α' },
    "cubic":        { 'b': 'a', 'c': 'a', 'α': 90., 'β': 90., 'γ': 90. }
}

lattice_settings = {
    "trigonal" : ["hexagonal", "rhombohedral"]
}

lattice_default_params = {
        'a' : 1.0,
        'b' : 1.3,
        'c' : 1.6,
        'α' : 80,
        'β':  100,
        'γ':  110
}

def complete_lattice_params(group, params):
    out = lattice_default_params.copy()
    out.update( { k:v for k,v in params.items() if v} )

    for k, v in lattice_fixed_params[group.lattice_type].items():
        if isinstance(v, float):
            out[k] = v
        else:
            out[k] = out[v]
    return out;

def lattice_from_params(params):
    """
    Return 3x3 lattice vectors (rows) in Cartesian coordinates for visualization.
    """
    return cellpar_to_cell([params[k] for k in lattice_default_params])


class WyckoffPosition:
    def __init__(self, wp):
        self.wp = wp

    @cached_property
    def dof_description(self) -> str:
        return self.wp.gen_pos().as_xyz_str().replace('"', '\\"')

    @cached_property
    def free_axes(self):
        frozen_axes = self.wp.get_frozen_axis()
        return [ax for ax in (0, 1, 2) if ax not in frozen_axes]

    @cached_property
    def dof_labels(self):
        frozen_axes = self.wp.get_frozen_axis()
        return [chr(ord('x') + ax) for ax in (0, 1, 2) if ax not in frozen_axes]

    @cached_property
    def multiplicity(self) -> int:
        return self.wp.multiplicity

    @cached_property
    def n_dofs(self) -> int:
        return self.wp.get_dof()

    @cached_property
    def letter(self) -> str:
        return self.wp.letter

    def ensure_free_dofs(self, vals:list[float]) -> list[float]:
        dofs = self.n_dofs
        ln = len(vals)
        if ln == dofs:
            return vals
        if ln > dofs:
            return vals[:dofs]
        else:
            return vals + [0.0] * (dofs - ln)

    def position_for_free_dofs(self, free_dofs: list[float]):
        free_dofs = self.ensure_free_dofs(free_dofs)
        return self.wp.get_position_from_free_xyzs(free_dofs)

    def all_positions_for_free_dofs(self, free_dofs: list[float])-> list[np.ndarray]:
        return self.wp.get_all_positions(self.position_for_free_dofs(free_dofs))

    def is_the_same_position(self, point: np.ndarray, tol: float = 1e-6) -> bool:
        """
        Checks if a given point can be generated by the Wyckoff position's parametrization.

        Parameters
        ----------
        point : point to check
        tol : float
            Tolerance for fractional comparisons.

        Returns
        -------
        bool
            True if wp_B/images_B can be obtained by parametrization of wp_A.
        """
        wp = self.wp
        p = wp.get_free_xyzs(point)
        # zrekonstruujeme bod z WP A
        p = wp.get_position_from_free_xyzs(p)
        # teprve teď testujeme, zda jsou skutečně ekvivalentní
        return wp.are_equivalent_pts(p, point, tol=tol)
